channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=22.2.2
- pip:
  - mlflow
  - defusedxml==0.7.1
  - fastai==2.7.9
  - google-cloud-storage==1.31.0
  - ipython==7.34.0
  - psutil==5.9.1
  - tables==3.6.1
  - timm==0.6.7
  - boto3
  - pyarrow
  - fsspec
  - s3fs
  - requests==2.26.0
  - gunicorn
  - pymongo
name: mlflow-env-stream
