datasets:
  minifigure_dataset:
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/tmp_test_predictions.parquet
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5


# TODO how to adapt to image data - no feature columns present
